services:
  facefusion-cuda:
    build:
      context: .
      dockerfile: Dockerfile.cuda
    command: [ "/bin/bash", "/facefusion/start.sh" ]
    volumes:
      - .assets:/facefusion/.assets
      - .caches:/facefusion/.caches
      - .jobs:/facefusion/.jobs
    ports:
      - 7870:7860  # Facefusion web UI (Gradio)
      - 8888:8888  # Jupyter Lab
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu, video ]
